name: Build and Deploy Emilia (Linux)

on:
  release:
    types: [released]
  workflow_dispatch:
    inputs:
      tag:
        description: "Release tag"
        required: false

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Download repo
        uses: actions/checkout@v6.0.2

      - name: Resolve tag
        run: |
          if [ -n "${{ github.event.release.tag_name }}" ]; then
              echo "TAG=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
          else
              echo "TAG=${{ github.event.inputs.tag }}" >> $GITHUB_ENV
          fi

      - name: Python Setup
        uses: actions/setup-python@v6.2.0
        with:
          python-version: '3.13'

      - name: Install Live2D
        run: |
          wget https://github.com/EasyLive2D/live2d-py/releases/download/v0.7.0.4/live2d_py-0.7.0.4-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl
          pip install live2d_py-0.7.0.4-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Download UPX
        run: |
          wget https://github.com/upx/upx/releases/download/v5.1.0/upx-5.1.0-amd64_linux.tar.xz
          tar -xf upx-5.1.0-amd64_linux.tar.xz
          mv upx-5.1.0-amd64_linux/upx .

      - name: Build with PyInstaller
        run: |
          LK_PATH=$(python -c "import livekit; print(list(livekit.__path__)[0])")
          L2D_PATH=$(python -c "import live2d, os; print(os.path.dirname(live2d.__file__))")
          
          pyinstaller --noconfirm --onedir --windowed \
            --icon "src/icon.ico" \
            --add-data "$LK_PATH/rtc/resources/liblivekit_ffi.so:livekit/rtc/resources" \
            --add-data "$L2D_PATH/v3/FrameworkShaders:live2d/v3/FrameworkShaders" \
            --hidden-import "urllib3.contrib.resolver.system" \
            --hidden-import "urllib3.contrib.hface.protocols.http1" \
            --hidden-import "urllib3.contrib.hface.protocols.http2" \
            --hidden-import "livekit.rtc.resources" \
            --hidden-import "OpenGL" \
            "src/main.py"
          
          cp "src/icon.ico" "dist/main/icon.ico"
          cp -r "src/lang" "dist/main/lang"
          cp -r "src/themes" "dist/main/themes"
          mkdir -p "dist/main/data"
          cp -r "src/data/default_qss" "dist/main/data/default_qss"
          
          if [ -f "dist/main/main" ]; then
              mv "dist/main/main" "dist/main/emilia"
          else
              exit 1
          fi

      - name: Cleanup Junk Files
        run: |
          python clean_dist.py

      - name: Create manifest
        run: |
          python create_manifest.py

      - name: Upload Artifact
        uses: actions/upload-artifact@v6
        with:
          name: app-build
          path: dist/main/
          retention-days: 1

      - name: Create Tarball Archive
        run: |
          tar -czf emilia-linux.tar.gz -C dist main

      - name: Upload Linux Archive Artifact
        uses: actions/upload-artifact@v6
        with:
          name: Emilia_Linux_Archive
          path: emilia-linux.tar.gz

      - name: Public release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG }}
          files: emilia-linux.tar.gz

  deploy:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        server: [ VPS, VPS2 ]
    steps:
      - name: Download Archive
        uses: actions/download-artifact@v4
        with:
          name: Emilia_Linux_Archive

      - name: Copy Archive
        uses: appleboy/scp-action@v1
        env:
          HOST: ${{ secrets[format('{0}_HOST', matrix.server)] }}
          USER: ${{ secrets[format('{0}_USER', matrix.server)] }}
        with:
          host: ${{ env.HOST }}
          username: ${{ env.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "emilia-linux.tar.gz"
          target: "/var/www/emilialinux"

      - name: Extract Archive
        uses: appleboy/ssh-action@v1
        env:
          HOST: ${{ secrets[format('{0}_HOST', matrix.server)] }}
          USER: ${{ secrets[format('{0}_USER', matrix.server)] }}
        with:
          host: ${{ env.HOST }}
          username: ${{ env.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/emilialinux
            tar -xzf emilia-linux.tar.gz --strip-components=1
            rm emilia-linux.tar.gz